baseURL = "https://morris3927.github.io/"
title = "Morris-blog"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production" # to enable google analytics, opengraph, twitter-cards and schema.
  title = "Morris blog"
  description = "Morris blog description"
  keywords = ["Blog", "Portfolio", "PaperMod", "Morris"]
  # author = "Me"
  # author = ["Me", "You"] # multiple authors
  # images = ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat = "January 2, 2006"
  defaultTheme = "auto" # dark, light
  disableThemeToggle = false                     # 是否禁用主題切換按鈕（深色/淺色），false 表示允許切換

  ShowReadingTime = true                         # 顯示文章預估閱讀時間
  # ShowShareButtons = true                      # 顯示社群分享按鈕（例如 Facebook、X），目前註解掉表示關閉
  ShowPostNavLinks = true                        # 顯示上下篇文章的導覽按鈕
  ShowBreadCrumbs = true                         # 顯示麵包屑導航（例如「首頁 > 技術 > 文章標題」）
  ShowCodeCopyButtons = true                     # 程式碼區塊右上角顯示「複製」按鈕
  ShowWordCount = true                           # 顯示文章字數
  ShowRssButtonInSectionTermList = true          # 在分類/標籤頁顯示 RSS 訂閱按鈕
  UseHugoToc = true                              # 使用 Hugo 內建的目錄功能（Table of Contents）
  disableSpecial1stPost = false                  # 是否取消第一篇文章的特殊樣式（例如加大或加圖），false 表示保留樣式
  disableScrollToTop = false                     # 是否關閉右下角「回到頂部」按鈕，false 表示開啟
  comments = false                               # 是否開啟留言系統（例如 Disqus）
  hidemeta = false                               # 是否隱藏文章的 meta 資訊（作者、日期、閱讀時間等），false 表示顯示
  hideSummary = false                            # 是否隱藏文章摘要（摘要會在首頁、分類頁出現），false 表示顯示
  showtoc = true                                # 是否顯示目錄（Table of Contents）區塊，false 表示不顯示（但可由 UseHugoToc 控制）
  tocopen = false                                # 預設是否展開目錄，false 表示收合


  [params.assets]
    # disableHLJS = true # to disable highlight.js
    # disableFingerprinting = true
    favicon = "/images/turtle.png"
    favicon16x16 = "/images/turtle.png"
    favicon32x32 = "/images/turtle.png"
    apple_touch_icon = "/images/turtle.png"
    safari_pinned_tab = "/images/turtle.png"

  [params.label]
    text = "Home"
    icon = "/apple-touch-icon.png"
    iconHeight = 35

  [params.profileMode]
    enabled = true
    title = "Morris Blog"
    subtitle = "重新回頭念書的工程師"
    imageUrl = "/images/turtle.png"
    imageWidth = 200
    imageHeight = 200
    imageTitle = "turtle-img"

    [[params.profileMode.buttons]]
      name = "技術"
      url = "posts/tech"

    [[params.profileMode.buttons]]
      name = "閱讀"
      url = "posts/read"

    [[params.profileMode.buttons]]
      name = "生活"
      url = "posts/life"

    [[params.profileMode.buttons]]
      name = "關於我"
      url = "/about"


  # [[params.socialIcons]]
  #   name = "x"
  #   url = "https://x.com/"

  # [[params.socialIcons]]
  #   name = "stackoverflow"
  #   url = "https://stackoverflow.com"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/"

  [[params.socialIcons]]
    name = "Instagram"
    url = "https://www.instagram.com/"


# [TODO] 上架後調整
  [params.analytics.google]
    SiteVerificationTag = "XYZabc"

  [params.analytics.bing]
    SiteVerificationTag = "XYZabc"

  [params.analytics.yandex]
    SiteVerificationTag = "XYZabc"

  [params.cover]
    hidden = true
    hiddenInList = true
    hiddenInSingle = true

  [params.editPost]
    URL = "https://github.com/morris3927-github.io/content"
    Text = "Suggest Changes"
    appendFilePath = true

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    limit = 10
    keys = ["title", "permalink", "summary", "content"]

[menu]

  [[menu.main]]
    identifier = "文章分類"
    name = "文章分類"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "標籤"
    name = "標籤"
    url = "/tags/"
    weight = 20

  # [[menu.main]]
  #   identifier = "example"
  #   name = "example.org"
  #   url = "https://example.org"
  #   weight = 30

  [[menu.main]]
    identifier = "所有文章"
    name = "所有文章"
    url = "/archives"
    weight = 20

  [[menu.main]]
    identifier = "關於我"
    name = "關於我"
    url = "/about"
    weight = 20


[markup]
  [markup.highlight]
    noClasses = false
    # anchorLineNos = true
    # codeFences = true
    # guessSyntax = true
    # lineNos = true
    # style = "monokai"
